namespace Game.Server.Packets
{
    public enum NewChickenBoxPackageType
	{
		ENTERCHICKENVIEW = 10,
		USEEAGLEEYE,
		TAKEOVERCARD = 13,
		FLUSHCHICKENVIEW,
		CLICKSTARTBNT,
		AllITEMSHOW = 12,
		CHICKENBOXOPEN = 1,
		CHICKENBOXCLOSE,
		GETITEMLIST,
		CANCLICKCARD = 5,
		TACKOVERCARD = 4,
		EAGLEEYE = 7,
		OVERSHOWITEMS = 6,
		ALL_GOODS_INFO = 21,
		REWARD_RECORD,
		GOODS_INFO,
		PLAY_REWARD_INFO,
		ACTIVITY_OPEN,
		ACTIVITY_END,
		AWARD_RANK,
		ENTER_GAME = 31,
		CLOSE_GAME,
		START_TURN,
		TURN_COMPLETE
	}
}
