namespace Game.Logic
{
	public enum eRoomType
	{
		Match = 0,
		Freedom = 1,
		Exploration = 2,
		Boss = 3,
        BattleRoom = 3,
        Dungeon = 4,
		FightLab = 5,
		Freshman = 10,
		Academy = 11,
        EliteGameScore = 12,
		EliteGameChampion = 13,
		Labyrinth = 0xF,
        Encounter = 0x10,
        FightGround = 18,
        ConsortiaBattle = 19,
        CoupleBoss = 20,
        SevenDouble = 31,
        CampBattleBattle,
        TransnationalFight = 22,
        AcademyDungeon,
        Lanbyrinth = 15,
        Entertainment = 41,
        EntertainmentPK = 42,
        ScoreLeage,
        FarmBoss = 28,
        GuildLeageRank,
        FightFootballTime = 30,
        EntertainmentRoom = 41,
        ActivityDungeon = 21,
        WordBossFight = 14,
        SpecialActivityDungeon = 27,
        Christmas = 40,
        RingStation = 24,
        SingleBattle,
        CatchBeast = 26,
        ConsortiaBoss = 17,
        EntertainmentRoomPK,
        ConsortiaMatchScore,
        ConsortiaMatchRank,
        ConsortiaMatchScoreWhole,
        ConsoritaMatchScoreRankWhole,
        SurvivalMode = 121,
        PolarRegion = 68
    }
}
